export default [
	{
		login: 'gui25',
		id: 31912784,
		node_id: 'MDQ6VXNlcjMxOTEyNzg0',
		avatar_url: 'https://avatars.githubusercontent.com/u/31912784?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/gui25',
		html_url: 'https://github.com/gui25',
		followers_url: 'https://api.github.com/users/gui25/followers',
		following_url: 'https://api.github.com/users/gui25/following{/other_user}',
		gists_url: 'https://api.github.com/users/gui25/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/gui25/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/gui25/subscriptions',
		organizations_url: 'https://api.github.com/users/gui25/orgs',
		repos_url: 'https://api.github.com/users/gui25/repos',
		events_url: 'https://api.github.com/users/gui25/events{/privacy}',
		received_events_url: 'https://api.github.com/users/gui25/received_events',
		type: 'User',
		site_admin: false,
	},
];
