export default {
  login: "john-smilga",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars3.githubusercontent.com/u/42133389?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/john-smilga",
  html_url: "https://github.com/john-smilga",
  followers_url: "https://api.github.com/users/john-smilga/followers",
  following_url:
    "https://api.github.com/users/john-smilga/following{/other_user}",
  gists_url: "https://api.github.com/users/john-smilga/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/john-smilga/subscriptions",
  organizations_url: "https://api.github.com/users/john-smilga/orgs",
  repos_url: "https://api.github.com/users/john-smilga/repos",
  events_url: "https://api.github.com/users/john-smilga/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/john-smilga/received_events",
  type: "User",
  site_admin: false,
  name: "John Smilga",
  company: "Coding Addict",
  blog: "www.johnsmilga.com",
  location: "Los Angeles",
  email: null,
  hireable: null,
  bio: "Creator of Coding Addict",
  twitter_username: "john_smilga",
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",
};

// {
//   "login": "JoaoGil06",
//   "id": 33355337,
//   "node_id": "MDQ6VXNlcjMzMzU1MzM3",
//   "avatar_url": "https://avatars.githubusercontent.com/u/33355337?v=4",
//   "gravatar_id": "",
//   "url": "https://api.github.com/users/JoaoGil06",
//   "html_url": "https://github.com/JoaoGil06",
//   "followers_url": "https://api.github.com/users/JoaoGil06/followers",
//   "following_url": "https://api.github.com/users/JoaoGil06/following{/other_user}",
//   "gists_url": "https://api.github.com/users/JoaoGil06/gists{/gist_id}",
//   "starred_url": "https://api.github.com/users/JoaoGil06/starred{/owner}{/repo}",
//   "subscriptions_url": "https://api.github.com/users/JoaoGil06/subscriptions",
//   "organizations_url": "https://api.github.com/users/JoaoGil06/orgs",
//   "repos_url": "https://api.github.com/users/JoaoGil06/repos",
//   "events_url": "https://api.github.com/users/JoaoGil06/events{/privacy}",
//   "received_events_url": "https://api.github.com/users/JoaoGil06/received_events",
//   "type": "User",
//   "site_admin": false,
//   "name": null,
//   "company": null,
//   "blog": "https://www.joaogildev.com/",
//   "location": "Porto, Portugal",
//   "email": null,
//   "hireable": null,
//   "bio": null,
//   "twitter_username": null,
//   "public_repos": 26,
//   "public_gists": 2,
//   "followers": 1,
//   "following": 3,
//   "created_at": "2017-11-03T16:41:08Z",
//   "updated_at": "2023-12-18T14:46:30Z"
// }
