export default {
	login: 'JoaoGil06',
	id: 33355337,
	node_id: 'MDQ6VXNlcjMzMzU1MzM3',
	avatar_url: 'https://avatars.githubusercontent.com/u/33355337?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/JoaoGil06',
	html_url: 'https://github.com/JoaoGil06',
	followers_url: 'https://api.github.com/users/JoaoGil06/followers',
	following_url: 'https://api.github.com/users/JoaoGil06/following{/other_user}',
	gists_url: 'https://api.github.com/users/JoaoGil06/gists{/gist_id}',
	starred_url: 'https://api.github.com/users/JoaoGil06/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/JoaoGil06/subscriptions',
	organizations_url: 'https://api.github.com/users/JoaoGil06/orgs',
	repos_url: 'https://api.github.com/users/JoaoGil06/repos',
	events_url: 'https://api.github.com/users/JoaoGil06/events{/privacy}',
	received_events_url: 'https://api.github.com/users/JoaoGil06/received_events',
	type: 'User',
	site_admin: false,
	name: 'João Gil',
	company: null,
	blog: 'https://www.joaogildev.com/',
	location: 'Porto, Portugal',
	email: null,
	hireable: null,
	bio: null,
	twitter_username: null,
	public_repos: 26,
	public_gists: 2,
	followers: 1,
	following: 3,
	created_at: '2017-11-03T16:41:08Z',
	updated_at: '2023-12-18T14:46:30Z',
};
